---
- name: install epel repo
  yum:
    name: epel-release
    state: present

- name: Disable SELinux
  selinux:
    state: disabled

- name: install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    validate_certs: no

- name: install postgresql server and barman
  yum:
    name:
      - postgresql12-server
      - barman
    state: present

- name: init db
  become_user: postgres
  shell:
    cmd: /usr/pgsql-12/bin/pg_ctl initdb -D /var/lib/pgsql/12/data

- name: remove pgdata
  file:
    path: "/var/lib/pgsql/12/data"
    state: absent

- name: create new pgdata
  file:
    path: "/var/lib/pgsql/12/data"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: copy base from master to slave
  become_user: postgres
  command: "pg_basebackup -h master -D /var/lib/pgsql/12/data -U replicator -P -R -X stream -C -S pgstandby1"
  notify: restart postgresql
